/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.RistoranteController;
import Model.RistoranteModel;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author Carmine Annunziata
 */
public class ModificaPietanzaFrame extends javax.swing.JFrame {

    /**
     * Creates new form AddPietanzaFrame
     */
    private RistoranteModel Rmod;
    private RistoranteController Rc;

    public ModificaPietanzaFrame() {
        this.setResizable(false);
        this.getContentPane().setBackground(Color.LIGHT_GRAY);
        this.setBounds(450, 250, 0, 0);
        initComponents();
        Rmod = new RistoranteModel();
        Rc = new RistoranteController(this, Rmod);
        SaveButton.addActionListener(Rc);
        AnnullButton.addActionListener(Rc);
        ModificaButton.addActionListener(Rc);
        CercaPietanzaButton.addActionListener(Rc);
        Font font1 = new Font("Segoe UI Semilight", Font.BOLD, 30);
        jTextField1.setEditable(false);
        jTextField1.setFont(font1);
        jTextField1.setHorizontalAlignment(JTextField.CENTER);
        jTextField1.setBackground(Color.orange);
        jTextField1.setHighlighter(null);

        NomePiatt.setEditable(false);
        NomePiatt.setBackground(Color.orange);
        NomePiatt.setHighlighter(null);

        Prezz.setEditable(false);
        Prezz.setBackground(Color.orange);
        Prezz.setHighlighter(null);

        Descrizion.setEditable(false);
        Descrizion.setBackground(Color.orange);
        Descrizion.setHighlighter(null);
    }

    // Metodi get e set
    public String getNamePietanza() {
        return NomePiatto.getText();
    }

    public String getDescrizionePietanza() {
        return Descrizione.getText();
    }

    public String getPrezzoPietanza() {
        return Prezzo.getText();
    }

    public String getTipoPortata() {
        return TipoPortata.getSelectedItem().toString();
    }

    public void setDescrizionePortata(String Descrizione) {
        this.Descrizione.setText(Descrizione);
    }

    public void setPrezzoPortata(String Prezzo) {
        this.Prezzo.setText(Prezzo);
    }
    /**
     * Il seguente metodo permette di capire quale sia la tipologia di portata
     * della seguente pietanza così da permetterci di modificarla secondariamente
     * a nostra scelta
     * @param Tipologia viene passata la tipologia di portata della pietanza scelta
     */
    public void setTipoPortata(String Tipologia) {
        int index = 0;
        if (Tipologia.equals("Antipasti")) {
            index = 0;
        }
        if (Tipologia.equals("Primi piatti")) {
            index = 1;
        }
        if (Tipologia.equals("Secondi")) {
            index = 2;
        }
        if (Tipologia.equals("Contorni")) {
            index = 3;
        }
        if (Tipologia.equals("Pizze")) {
            index = 4;
        }
        if (Tipologia.equals("Frutta")) {
            index = 5;
        }
        if (Tipologia.equals("Dessert")) {
            index = 6;
        }
        this.TipoPortata.setSelectedIndex(index);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        NomePiatt = new javax.swing.JTextField();
        NomePiatto = new javax.swing.JTextField();
        Descrizion = new javax.swing.JTextField();
        Descrizione = new javax.swing.JTextField();
        Prezz = new javax.swing.JTextField();
        Prezzo = new javax.swing.JTextField();
        TipoPortata = new javax.swing.JComboBox<>();
        SaveButton = new javax.swing.JButton();
        AnnullButton = new javax.swing.JButton();
        CercaPietanzaButton = new javax.swing.JButton();
        ModificaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modifica/Elimina Pietanza");
        setFocusTraversalPolicyProvider(true);

        jTextField1.setText("Scegliere la pietanza da modificare o rimuovere al menù");

        NomePiatt.setFont(new java.awt.Font("Segoe UI Semilight", 1, 13)); // NOI18N
        NomePiatt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NomePiatt.setText("NOME PIATTO");

        Descrizion.setFont(new java.awt.Font("Segoe UI Semilight", 1, 13)); // NOI18N
        Descrizion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Descrizion.setText("DESCRIZIONE");

        Prezz.setFont(new java.awt.Font("Segoe UI Semilight", 1, 13)); // NOI18N
        Prezz.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Prezz.setText("PREZZO");

        TipoPortata.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        TipoPortata.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Antipasti", "Primi piatti", "Secondi", "Contorni","Pizze","Frutta","Dessert"}));

        SaveButton.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        SaveButton.setForeground(new java.awt.Color(102, 0, 102));
        SaveButton.setText("RIMUOVI");

        AnnullButton.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        AnnullButton.setForeground(new java.awt.Color(102, 0, 153));
        AnnullButton.setText("ANNULLA.");

        CercaPietanzaButton.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        CercaPietanzaButton.setForeground(new java.awt.Color(102, 0, 102));
        CercaPietanzaButton.setText("Cerca Pietanza");

        ModificaButton.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        ModificaButton.setForeground(new java.awt.Color(102, 0, 102));
        ModificaButton.setText("MODIFICA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NomePiatt, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Descrizion, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(ModificaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AnnullButton, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(NomePiatto)
                                    .addComponent(Descrizione, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(5, 5, 5)
                                .addComponent(CercaPietanzaButton)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Prezz, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Prezzo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TipoPortata, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(NomePiatt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(NomePiatto, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Prezz, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Prezzo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(CercaPietanzaButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Descrizion, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Descrizione, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TipoPortata, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AnnullButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ModificaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificaPietanzaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificaPietanzaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificaPietanzaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificaPietanzaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificaPietanzaFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnnullButton;
    private javax.swing.JButton CercaPietanzaButton;
    private javax.swing.JTextField Descrizion;
    private javax.swing.JTextField Descrizione;
    private javax.swing.JButton ModificaButton;
    private javax.swing.JTextField NomePiatt;
    private javax.swing.JTextField NomePiatto;
    private javax.swing.JTextField Prezz;
    private javax.swing.JTextField Prezzo;
    private javax.swing.JButton SaveButton;
    private javax.swing.JComboBox<String> TipoPortata;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
